Add materials loading status handling
ita-social-projects/dokazovi-fe pull request #128
Opened 2020-12-09 11:42 UTC by calster00

## GitHub Board

**Issue link**

[#127 Direction: Rework fetchMaterials to use createAsyncThunk ](https://github.com/ita-social-projects/dokazovi-fe/issues/127 )

## Code reviewers
- [ ] @github_username

## Summary of issue
- [x] Add extended loading status handling in separate reducer.
- [x] Use LoadingInfo in MaterialsContainer.

2020-12-10 09:31 UTC, SergeOlabin reviewed
are we planning to re write to async thunk after introducing router to the store so that we could access `direnctionName` on loading?

2020-12-10 09:52 UTC, calster00 commented
> are we planning to re write to async thunk after introducing router to the store so that we could access `direnctionName` on loading?

We gave up on that idea, since it has turned out we can't access root state (where current route is stored) from `directionSlice extraReducers` – they only get `directions` state slice. That is why I update loading status manually using `setMaterialsLoadingStatus`.

2020-12-10 09:55 UTC, calster00 reviewed
> are we planning to re write to async thunk after introducing router to the store so that we could access direnctionName on loading?

We gave up on that idea, since it has turned out we can't access root state (where current route is stored) from directionSlice extraReducers – they only get directions state slice. That is why I update loading status manually using setMaterialsLoadingStatus.

2020-12-10 11:54 UTC, calster00 reviewed
added thunk for initial posts load, ready for merge

2020-12-10 11:55 UTC, SergeOlabin approved these changes

2020-12-11 09:51 UTC, SergeOlabin requested changes
pls resolve conflicts

2020-12-11 09:51 UTC, SergeOlabin commented on src/modules/direction/components/MaterialsContainer.tsx
> +      setMaterialsLoadingStatus({
pls put it to `fetchMaterials` so that fetchMaterials will handle loading status each time.
you are doing the same for initial loading

2020-12-11 09:51 UTC, SergeOlabin commented on src/modules/direction/store/directionSlice.ts
> +    dispatch(fetchMaterials(direction));
why do we set loading only in case these's no posts but don't fetch the posts themselves?

2020-12-14 10:23 UTC, merged