router logic for post view
ita-social-projects/dokazovi-fe pull request #195
Opened 2021-01-11 18:01 UTC by darya42185

develop
https://github.com/ita-social-projects/dokazovi-fe/issues/159
[#159]
[#159 Story]( )

2021-01-14 11:28 UTC, SergeOlabin requested changes

2021-01-14 11:28 UTC, SergeOlabin commented on src/modules/posts/components/PostProfileView.tsx
> +const PostProfileView: React.FC = () => {
PostProfileView looks line not a good name.. PostProfice - seems like not applicable one

is this component PostView?

2021-01-14 11:28 UTC, SergeOlabin commented on src/modules/posts/store/postsSlice.ts
> +/* eslint-disable @typescript-eslint/no-unsafe-assignment */
fix eslint errors pls

2021-01-14 11:28 UTC, SergeOlabin commented on src/modules/posts/components/PostProfileView.tsx
> +const PostProfileView: React.FC = () => {
seems like this is PostView that we discussed

2021-01-14 11:28 UTC, SergeOlabin commented on src/store/rootReducer.ts
> +/* eslint-disable import/named */
why adding this?

2021-01-14 11:28 UTC, SergeOlabin commented on src/modules/posts/store/postsSlice.ts
> +  materials: {} as IMaterialsState,
what are materials used for?

2021-01-14 11:28 UTC, SergeOlabin commented on src/modules/posts/components/PostProfileView.tsx
> +  const dispatch = useDispatch();
that's not good..
a single post component should not know anything about all loaded posts.

so let's siplify the stuff here:
- just parse the `id` from the url and get the post and display it
- if there's no post with such an id show 404 error (for now, might be a more informative message latter)
- don't use store to store all loaded posts 
- don't store it in the redux for now

let's not use caching in any form for now, for just displaying the post it looks like obsolete

2021-01-20 16:00 UTC, SergeOlabin requested changes

2021-01-20 16:00 UTC, SergeOlabin commented on src/modules/postCreation/ArticleCreationPreview.tsx
> +      <PostPreview draft={draft} />
use PostView here

2021-01-20 16:00 UTC, SergeOlabin commented on src/modules/posts/components/PostPreview.tsx
> +import React from 'react';
this is redundant, it is the same as PostView

2021-01-20 16:22 UTC, AntonGluschuk commented on debug.log
> +[0115/150555.364:ERROR:directory_reader_win.cc(43)] FindFirstFile: ������� �� ������� ����� ��������� ����. (0x3)
fixed

2021-01-20 16:22 UTC, AntonGluschuk commented on src/navigation/router-config.tsx
> +    component: PostView,
fixed

2021-01-20 16:38 UTC, AntonGluschuk commented on src/modules/posts/components/PostView.tsx
> +          <Typography className={classes.content}>{post.content}</Typography>
fixed

2021-01-20 16:39 UTC, AntonGluschuk commented on src/modules/postCreation/ArticleCreationView.tsx
> +  const articlePreview = () => {
fixed

2021-01-20 16:44 UTC, AntonGluschuk commented on src/modules/postCreation/ArticleCreationPreview.tsx
> +  const articleCreationView = () => {
fixed

2021-01-20 16:44 UTC, AntonGluschuk commented on src/modules/postCreation/ArticleCreationView.tsx
>  const ArticleCreationView: React.FC = () => {
fixed

2021-01-21 10:21 UTC, SergeOlabin approved these changes

2021-01-21 10:26 UTC, merged