Post view restyling
ita-social-projects/dokazovi-fe pull request #275
Opened 2021-02-23 20:39 UTC by darya42185

develop
https://github.com/ita-social-projects/dokazovi-fe/issues/264

2021-02-24 17:44 UTC, SergeOlabin commented on src/lib/theme/typography.ts
> +  dataCreatedAt: {
```suggestion
  dateCreatedAt: {
```

2021-02-24 17:44 UTC, SergeOlabin commented on src/modules/posts/styles/PostViewInfo.styles.ts
>      marginTop: '20px',
pls use `theme.spacing()` here

2021-02-24 17:44 UTC, SergeOlabin commented on src/modules/posts/styles/PostViewInfo.styles.ts
> +    margin: '20px',
pls use theme.spacing() here

2021-02-24 17:44 UTC, SergeOlabin commented on src/modules/posts/styles/PostViewInfo.styles.ts
>      margin: '20px',
pls use theme.spacing() here

2021-02-24 17:44 UTC, SergeOlabin commented on src/modules/posts/styles/PostViewInfo.styles.ts
> +    color: '#3B6F95',
pls use theme.palette here

2021-02-24 17:44 UTC, SergeOlabin commented on src/modules/posts/styles/PostViewInfo.styles.ts
> +    lineHeight: '24px',
i think you should be able to use themming here

2021-02-24 17:44 UTC, SergeOlabin commented on src/modules/posts/components/PostView.tsx
> +    <ThemeProvider theme={MAIN_THEME}>
we have it provided in root , don't need here

2021-03-03 10:19 UTC, SergeOlabin requested changes

2021-03-03 10:19 UTC, SergeOlabin commented on public/index.html
> +    <div id="root"></div>
duplicate

2021-03-03 11:03 UTC, darya42185 commented on public/index.html
> +    <div id="root"></div>
fixed

2021-03-03 15:44 UTC, SergeOlabin requested changes
pls resolve conflicts

2021-03-03 15:44 UTC, SergeOlabin commented on public/index.html
> +    <div id="root"></div>
duplicate

2021-03-03 15:44 UTC, SergeOlabin commented on public/index.html
> +    <noscript>You need to enable JavaScript to run this app.</noscript>
pls move below the links

2021-03-09 10:31 UTC, dusty3ntity approved these changes

2021-03-09 10:47 UTC, merged