#22 add preview component
ita-social-projects/dokazovi-fe pull request #32
Opened 2020-11-11 14:16 UTC by tania833

develop

## GitHub Board

**Issue link**

[#22  ]( )

**Story link**

[#22 ]( )

## Code reviewers
- [ ] @github_username

## Summary of issue

- [ ]  Summary of issue
- [ ]  Summary of issue

## Summary of change

- [ ]  Summary of change
- [ ]  Summary of change

2020-11-11 14:59 UTC, SergeOlabin requested changes

2020-11-11 14:59 UTC, SergeOlabin commented on src/lib/components/ExpertBlock.tsx
> +}
```suggestion
interface IExpertProps{
  expert: IExpert, // imported from lib/types.ts
}
```

2020-11-11 14:59 UTC, SergeOlabin commented on src/lib/components/ExpertBlock.tsx
> +};
pls don't do that.

you can create another variable for 
```
{infoCards.map((card) => {
    return (
      <div className="col m3" key={card.phone}>
        <div className="card small">
          <div className="card-image waves-effect waves-block waves-light">
            <img className="activator" src={card.photo} alt="doctor" />
          </div>
        </div>
      </div>
    );
  })}
```
and use it

2020-11-11 14:59 UTC, SergeOlabin commented on src/lib/constants/mockDataCards.tsx
> +import { IExpert, ExpertStatus } from '../types';
move to modules/experts,

the content is nice!

2020-11-11 14:59 UTC, SergeOlabin commented on src/lib/components/ExpertBlock.tsx
> +      <h4>Experts</h4>
remove header,
this component should be related to the only 1 expert card

2020-11-12 09:07 UTC, SergeOlabin requested changes

2020-11-12 09:07 UTC, SergeOlabin commented on src/lib/components/ExpertBlock.tsx
> +};
expert block should be per 1 expert

2020-11-12 09:07 UTC, SergeOlabin commented on src/lib/components/ExpertBlock.tsx
> +  expert: IExpert[];
expert: IExpert

2020-11-12 09:25 UTC, tania833 commented on src/lib/components/ExpertBlock.tsx
> +  expert: IExpert[];
done

2020-11-12 09:25 UTC, tania833 commented on src/lib/components/ExpertBlock.tsx
> +};
done

2020-11-12 10:08 UTC, SergeOlabin approved these changes

2020-11-12 10:08 UTC, SergeOlabin commented on src/lib/components/Experts.tsx
> +  const allExperts = cards.map((card) => {
Cool!

2020-11-12 10:08 UTC, merged